### ISSUE TITLE
Unable to get android-apt to work with Android Studio 1.5 or 2.0, gradle rev 2.8

### ISSUE THREAD

**Issue by Trellian** [memtrip/SQLKing#1]
Hi,

I've just tried to update to the new version of SQLKing. It is completely different from the first version, and has several dependencies. One of them is the android-apt plugin, but I can't get gradle to recognise 'apt'. 

Have you perhaps got a small demo project that implements a full SQLKing example?

Thanks in advance,
Adrian

**Comment by samkirton** [comment]
Hi Adrian,

Use these dependencies:
`dependencies {
    apt 'com.memtrip.sqlking:preprocessor:1.0.4'
    compile 'com.memtrip.sqlking:client:1.0.5'
}`

I did not update the documentation for the latest version, sorry about that.

I will create a sample project, but for now take a look at:
https://bitbucket.org/hvisser/android-apt

It explains how to use the android-apt plugin, which runs the annotation preprocessor.

Cheers,
Sam

**Comment by Trellian** [comment]
Hi Sam,

Thanks for that, and the very prompt response. I'm just busy installing the latest Studio 
updates and Gradle 2.12, the moment it is done I will give it a shot.

However, I have had a long look at https://bitbucket.org/hvisser/android-apt. The 
following issue: 
https://bitbucket.org/hvisser/android-apt/issues/33/support-for-jack-and-jill has a 
discussion around the compatibility with the new gradle-plugin.

I will likely have to take it up with Hugo.

What IDE and tool versions are you using?  Maybe that will help me to get a handle on how 
to fix this.

Thanks, and best regards,
Adrian

**Comment by samkirton** [comment]
I added a sample project:
https://github.com/memtrip/SQLKing/tree/master/sample

Cheers,
Sam

**Comment by Trellian** [comment]
Thank you very much for the help Sam, it's appreciated!.

My very best regards,
Adrian
