### ISSUE TITLE
Error in client/build.gradle - requesting old version of preprocessor

### ISSUE THREAD

**Issue by Trellian** [memtrip/SQLKing#12]
Hi Sam, 

While trying to install the client locally (for release 1.1), I discovered the following in the client/build.gradle:

androidTestApt 'com.memtrip.sqlking:preprocessor:1.0.17'

After changing the version:

androidTestApt 'com.memtrip.sqlking:preprocessor:1.1'

The client now successfully builds.

JTYSK ;)
Adrian

**Comment by samkirton** [comment]
Fixed!
