### ISSUE TITLE
Duplicate definitions being generated in retrieveSQLSelectResults

### ISSUE THREAD

**Issue by Trellian** [memtrip/SQLKing#14]
Hi Sam, 

I have a table that has two FK's in it as follows:

```
public class TblMapVisitor2Entry extends BaseObservable implements Parcelable
    {
    @Column(index = true) private int       id;
    @Column private TblEntry   tblEntry;
    @Column private TblVisitor tblVisitor;

```

and in Q.Java, I get an error on duplicate symbols as follows:

```
      for (int i = 0; !cursor.isAfterLast(); i++) {
        com.thorburn.sanscan.scanDB.TblMapVisitor2Entry tblmapvisitor2entry =
            new com.thorburn.sanscan.scanDB.TblMapVisitor2Entry();

        com.thorburn.sanscan.scanDB.TblEntry tblentry = new com.thorburn.sanscan.scanDB.TblEntry();
        tblmapvisitor2entry.setTblEntry(tblentry);

        com.thorburn.sanscan.scanDB.TblVisitor tblvisitor =
            new com.thorburn.sanscan.scanDB.TblVisitor();
        tblmapvisitor2entry.setTblVisitor(tblvisitor);

        com.thorburn.sanscan.scanDB.TblEntry tblentry = new com.thorburn.sanscan.scanDB.TblEntry();
        tblmapvisitor2entry.setTblEntry(tblentry);

        com.thorburn.sanscan.scanDB.TblVisitor tblvisitor =
            new com.thorburn.sanscan.scanDB.TblVisitor();
        tblmapvisitor2entry.setTblVisitor(tblvisitor);

```

You can see that 'tblentry' and 'tblvisitor' variables are being declared twice.  I have had a look at the preprocessor template source for Q.Java but can't see how it could be happening. I'm currently taking a shot at fixing it, but not having much success.

Please can you take a look?

Thanks,
Adrian

**Comment by samkirton** [comment]
Hi Adrian,

Could you paste the source of "BaseObservable" also?

Cheers,
Sam

**Comment by Trellian** [comment]
Hi Sam,

You can see the source here: 
https://android.googlesource.com/platform/frameworks/data-binding/+/c9a5d6f140f732ca0ff279a4b1ee315072e1c422/library/src/main/java/android/databinding/BaseObservable.java

Thanks for the quick response!

/Adrian

**Comment by Trellian** [comment]
BaseObservable is being used because I'm using the new 2-way DataBinding features, instead 
of Butterknife

/Adrian

**Comment by Trellian** [comment]
I have tried this in Q.Java (starting at line 167 - in retrieveSQLSelectResults):

I'm building a list of columns already processed for the table, to avoid generating duplicates.

```
                for (int i = 0; !cursor.isAfterLast(); i++) {
                    ${packagedTableName} ${table.getName()?lower_case} = new ${packagedTableName}();
                    <#assign colsProcessed=[]>
                    <#list table.getColumns() as column>
                        <#if column.isJoinable(tables) >
                            <#if colsProcessed?seq_contains(column.getName()) != true>
                            ${joinReferences(table.getName(),tables)}
                                <#assign colsProcessed = colsProcessed + [column.getName()]>
                            </#if>
                        </#if>
                    </#list>

```

Preprocessor builds fine, but final Q.Java doesn't generate now, so obviously I've made a stupid mistake.

**Comment by samkirton** [comment]
If the final Q doesn't generate it will be a FreeMarker issue, if you build the project with `mvn clean install -X` it should be logged. 

Also is 2 way binding available in the support library?

**Comment by Trellian** [comment]
I've got the final Q to generate now, it still has the double declarations, but FreeMarker 
seems happy for now.

One thing that concerns me is that the Maven Install installs to:
C:\Users\Adrian.m2\repository\com\memtrip\sqlking\preprocessor\1.0.15\preprocessor-1.0.15.jar

And it looks like my gradle build of my project is using what it has in it's cache at

C:\Users\Adrian\m2repository\com\memtrip\sqlking\preprocessor\1.0.15\preprocessor-1.0.15.jar

I couldn't find a way to point either one to a consolidated maven repository.

Have you experienced this before?

Regards,
Adrian

**Comment by samkirton** [comment]
On the client project it might be worth using: 
`gradle build --refresh-dependencies`

Also its probably best if you stash your changes and see if you can reproduce the issue, it might have been fixed in 1.1, 1.0.15 is quite old!

**Comment by Trellian** [comment]
I'm a bit confused here... it turns out that I was indeed using 1.1, but changes to my local 1.0.15 showed up as compile errors in my client project?

Anyway, I have moved to 1.1, the original problem still exists with the duplicate declarations.

Any Ideas?

Thanks,
Adrian

**Comment by samkirton** [comment]
Hi Adrian,

Please see the fix/duplicate_relationships branch, the issue has been fixed. I will push a release to maven central tonight.

Cheers,
Sam

**Comment by Trellian** [comment]
Hi Sam, 
Did you get a chance to push a release to Maven?

Thanks,
Adrian

**Comment by samkirton** [comment]
All deployed.

Cheers,
Sam

**Comment by Trellian** [comment]
Thanks Sam, works like a charm!
