### ISSUE TITLE
Request for ability to ignore private static member variables in a Table

### ISSUE THREAD

**Issue by Trellian** [memtrip/SQLKing#4]
Hi Sam,

I would like to be able to either ignore static members, or specifically to ignore one called "CREATOR".

This would allow for adding parcelable implementation to a Table. 

Would this be possible?

I think it could be done without too much trouble, as follows in Column.Java:

`
private List<Column> assembleMembers(Element element) {
        List<Column> columns = new ArrayList<>();

```
    if (element.getEnclosedElements() != null && element.getEnclosedElements().size() > 0) {
        for (Element childElement : element.getEnclosedElements()) {
            if (childElement.getKind().isField()) {
                **if (!childElement.getSimpleName().toString().equals("CREATOR")) {**
                    columns.add(new Column(childElement));
                }
            }
        }
    }

    return columns;
}`
```

**Comment by Trellian** [comment]
Apologies, Table.java

**Comment by samkirton** [comment]
I think it would be better to check if `childElement` is annotated with @Column? That way it would ignore all other members. You can make the change and raise a pull request if you want? Otherwise I can add this later.

**Comment by samkirton** [comment]
Fixed in https://github.com/memtrip/SQLKing/pull/5 and merged with master
