### ISSUE TITLE
Unable to locate the 'Q' class

### ISSUE THREAD

**Issue by Trellian** [memtrip/SQLKing#6]
Hi Sam, 

Everything is resolving, except for the Q class. Can you give me a quick rundown of what I should do to configure this?

Also, I had to add 
    compile 'com.memtrip.sqlking:common:1.0.4'" to my build.gradle, alongside
    apt 'com.memtrip.sqlking:preprocessor:1.0.4' and 
    compile 'com.memtrip.sqlking:client:1.0.5'

Thanks!

**Comment by samkirton** [comment]
The Q class is generated in the preprocessor step, try reimporting the project into Android Studio? You should get a build error if Q fails to get generated.

**Comment by Trellian** [comment]
Ok, I re-imported the project as a module, but I think that the Q class is not being generated. I have raised a new issue with the details of the problem related to this. If that issue sorts it out, then you can probably close this issue
