### ISSUE TITLE
How to do join queries?

### ISSUE THREAD

**Issue by Trellian** [memtrip/SQLKing#9]
Hi Sam, 

Have you got a simple example of a query involving a join between two tables?

Thanks,
Adrian

**Comment by samkirton** [comment]
Hi Adrian,

The next build will have support for join, it will be with you Monday.

Cheers,
Sam

**Comment by samkirton** [comment]
For an inner join example please see:

https://github.com/memtrip/SQLKing/blob/master/sample/app/src/main/java/com/memtrip/sqlking/sample/comment/CommentActivity.java#L144
